name: Release Publisher

on: 
  workflow_call:
    inputs:
      publish:
        required: false
        default: true
        type: boolean
      version:
        required: true
        type: string

permissions:
  contents: read

jobs:
  publish_release:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Set version env
        run: |
          RELEASE_VERSION="${{ inputs.version }}";
          if [ -z "$RELEASE_VERSION" ]; then
            RELEASE_VERSION="${GITHUB_REF#refs/*/}"
          fi;
          echo RELEASE_VERSION=$RELEASE_VERSION >> $GITHUB_ENV

          MINOR=${RELEASE_VERSION%.*}
          MINOR=${MINOR#v}
          TARGET=release/${MINOR}
          if [[ "${GITHUB_REF#refs/*/}" -eq "master" ]]; then
            TARGET="master"
          fi
          echo RELEASE_TARGET=$TARGET >> $GITHUB_ENV
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          disable-autolabeler: true
          name: ${{ env.RELEASE_VERSION }}
          tag: ${{ env.RELEASE_VERSION }}
          version: ${{ env.RELEASE_VERSION }}
          commitish: ${{ env.RELEASE_TARGET }}
          publish: ${{ inputs.publish }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}