name: Release Drafter LTS12

on:
  push:
    branches:
      - release/12.0
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "release/12.0"
      - uses: release-drafter/release-drafter@v6
        with:
          # the drafter template lives on 'master', no need to add it to this release branch!
          config-name: release-drafter-lts12.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
